### ISSUE TITLE
[Feature Request] External Authentication Backends

### ISSUE THREAD

**Issue by deathbybandaid** [linkwarden/linkwarden#224] opened 2023-10-13 11:42 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'd like to see external authentication, such as Radius, LDAP, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
For my homelab purposes, I like to use applications that I can use SSO to log into my services wherever possible.

For the business that I work at, it would be very beneficial for my users to be able to use a tool like this and authenticate against our local Active Directory server.

**Comment by arcoast** [comment] 2023-10-13 19:56
I'd second this too, I'd have a preference for OIDC myself, but agree any sort of SSO would be a major step forwards.

**Comment by sabirovrinat85** [comment] 2023-10-26 18:30
Second this, that feature is really important.

Some of the examples from (maybe) dropped project with the kind of same purpose, named Briefkasten:

[nextauth.js](https://github.com/ndom91/briefkasten/blob/main/src/pages/api/auth/%5B...nextauth%5D.js)
[example for .env](https://github.com/ndom91/briefkasten/blob/main/.env.example)

**Comment by cxqeric** [comment] 2023-10-27 00:19
> Some of the examples from (maybe) dropped project with the kind of same purpose, named Briefkasten:

dropped ？Where did you see it and why do you say that?

**Comment by mpldr** [comment] 2023-10-28 20:08
It seems to be relatively uncomplicated to add the functionality
- https://github.com/nextauthjs/next-auth-example

and instructions for adding OIDC/OAuth2 support:
- https://thetombomb.com/posts/nextjs-nextauth-okta

Anyone taking this on, feel free to ping me for testing.

**Comment by mirceanton** [comment] 2023-10-30 19:20
This is something I am also interested in. +1 for OIDC

**Comment by Jacq** [comment] 2023-11-06 11:10
This looks as a duplicate of #193

**Comment by daniel31x13** [comment] 2023-11-25 05:08
Added Keycloak integration in [v2.3.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.3.0).

**Comment by daniel31x13** [comment] 2023-12-27 23:42
Added in [v2.4.0](https://github.com/linkwarden/linkwarden/releases/tag/v2.4.0).

**Closed by daniel31x13** 2023-12-27 23:42 UTC

**Comment by Bykow** [comment] 2023-12-31 10:18
Hello !

Thank you for adding OIDC to the project. Impressive list of provider, yet [Authelia](https://www.authelia.com/) is missing, could it be added ? It's a "simpler" alternative to Authentik.
