### ISSUE TITLE
"Open all Links" option within Collection doesn't open all links -- only first link in collection is opened

### ISSUE THREAD

**Issue by jordanhandy** [linkwarden/linkwarden#888] opened 2024-11-24 04:13 UTC
**Describe the bug**
- Under a Collection, when trying to use the "Open all Links" option, only the very first item in the collection is opened as a new tab.  All other links are ignored

**To Reproduce**

1. Open any collection with multiple links
2. Select "Open all Links"
3. See only one tab opened.  This is the link to the first item in the collection -- no other tabs are opened

**Expected behavior**
When "Open all Links" is clicked under a collection.  All collection items should be opened as separate tabs

**Screenshots**
<img width="310" alt="image" src="https://github.com/user-attachments/assets/3255e9c2-0dd1-4604-b9b9-157eff0fa4e0">
**Desktop (please complete the following information):**
 - OS: macOS Sequoia
 - Browser: Google Chrome
 - Browser Version 131
 - Linkwarden Version: 2.8.3

**Additional context**
Tried on multiple Chromium browsers.  Same issue -- Opera, Vivaldi

**Comment by daniel31x13** [comment] 2024-11-26 13:59
Duplicate of #853

**Closed by daniel31x13** 2024-11-26 13:59 UTC
Labels: bug
