### ISSUE TITLE
Admin page / User management ?

### ISSUE THREAD

**Issue by SylvainDx** [linkwarden/linkwarden#616] opened 2024-06-05 13:42 UTC
Hello,

I'm new and just discovering your product.
I was wondering if there is an existing Admin page to add, modify, invite users
As it is possible to disable new account creation, this will allow to manage existing ones

Thank you by advance, and maybe even sorry if I miss an item describing this topic in the github ;)

**Comment by daniel31x13** [comment] 2024-06-10 12:17
Duplicate of #217, it'll be out in the next release.

**Closed by daniel31x13** 2024-06-10 12:17 UTC
Labels: question
