### ISSUE TITLE
Infinite requests on brand new install

### ISSUE THREAD

**Issue by bobslaede** [linkwarden/linkwarden#504] opened 2024-03-07 18:53 UTC
**Describe the bug**
Fresh install with keycloak as auth. Signed in, and immediately the logs just spam requests to the postgresql server.  
Notice the log in the browser is just spamming the backend and getting redirected.  

Added a link to be saved, and the whole thing stopped being weird. 

**Expected behavior**
Expected Linkwarden to behave :) 

**Screenshots**
![image](https://github.com/linkwarden/linkwarden/assets/437918/bc8226be-9896-4d72-8d65-933604d8846a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser Firefox
 - Version 123.0.1 (64-bit)

**Comment by daniel31x13** [comment] 2024-03-07 19:18
I thought I fixed that already, does it persist if you refresh the page one more time?

**Comment by bobslaede** [comment] 2024-03-08 06:28
Deleting all links and collections makes the problem come back. Refreshing does not help.

**Comment by daniel31x13** [comment] 2024-03-08 06:31
So even if you have a single collection, the issue is prevented right?

**Comment by bobslaede** [comment] 2024-03-08 06:34
Yes, with a single collection there is no issue.

**Comment by daniel31x13** [comment] 2024-03-08 06:44
Got it, gonna fix it in the next release.

**Comment by daniel31x13** [comment] 2024-03-10 17:56
Fixed in [v2.5.1](https://github.com/linkwarden/linkwarden/releases/tag/v2.5.1).

**Closed by daniel31x13** 2024-03-10 17:56 UTC
Labels: bug
