### ISSUE TITLE
Scrolling a Category in Details mode does not lazy load additional links.

### ISSUE THREAD

**Issue by MYX-GitHub** [linkwarden/linkwarden#452] opened 2024-02-02 16:50 UTC
Scrolling a large collection lazy loads additional links when set to Tile mode. If the Category is displayed in Detail mode, scrolling to the bottom of the list does not lazy load additional links, and you cannot see more links.

**Expected behavior**
The links should continue to lazy load when scrolling to the bottom until you reach the end of the collection, regardless of whether links are displayed as tiles or detail lines.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version 115.7.0esr

**Comment by daniel31x13** [comment] 2024-02-02 17:08
In both views I couldn't reproduce this bug, could you please elaborate a bit more?

![image](https://github.com/linkwarden/linkwarden/assets/93432314/2e850ef2-70fe-4fee-88b9-8ccf55933011)

**Comment by MYX-GitHub** [comment] 2024-02-02 17:28
Sure. I exported about 6K bookmarks from LinkStash as an HTML file, then imported the HTML into Linkwarden. There were a few glitches, but overall it worked well. Folders in LinkStash were recreated as Categories, with an interesting side-effect - Clicking a Category would display the links in that category as well as all the links that were in the LinkStash subfolders!

When I clicked on a Category with a few hundred links, it would lazy load a few screens of tiles. Scrolling down to the bottom would cause a few more screens of tiles to be loaded. This would work until I reached the end of the list of links.

If I do the same thing with the same Category in Detail line mode, it would lazy load a few screens of links as detail lines, as before, but when I scroll to the bottom, it would not load any more links., giving the impression that I've come to the end of the links.

I deleted that user account (and all the links) so I cannot reproduce the bug. I LOVE the concept of Linkwarden and think it will go far, but until it stabilizes a bit, I am only using it on a subset of my bookmarks. I can re-import my LinkStash repository if that helps. (BTW - LinkStash from XRayz Software is great bookmark manager, but it is stagnating, and eventually I will have to migrate to something else, which is why I'm looking at Linkwarden. Even at this early stage, Linkwarden gets 2 thumbs up!!!)

**Comment by etec-masterofsynapse** [comment] 2024-02-11 21:53
In danger of hijacking this issue with a different problem, here is the description of my similar problem:

I run 4K resolution, and lazy loading of links doesn't work at all, so both views have that problem.
I have to zoom in, scroll down and up a few times, set zoom to standard and then the rest of the links load correctly when scrolling down.

If I don't do this, it loads the first 20 links (which fit on the screen completely), and scrolling does absolutely nothing.

**Comment by daniel31x13** [comment] 2024-02-12 19:07
> I run 4K resolution
I think I know what's happening now @MYX-GitHub is your monitor +4K as well?

As a temporary fix you can include the following in the environment variables:
```
PAGINATION_TAKE_COUNT=50
```

What happens is it shows 50 links instead of 20 on every scroll to bottom.

**Comment by daniel31x13** [comment] 2024-02-12 19:07
> I run 4K resolution

I think I know what's happening now, @MYX-GitHub is your monitor +4K as well?

As a temporary fix you can include the following in the environment variables:
```
PAGINATION_TAKE_COUNT=50
```

What happens is it shows 50 links instead of 20 on every scroll to bottom.

**Comment by daniel31x13** [comment] 2024-02-15 13:21
Got it, so I'll be closing this issue for now.
Let me know if you still encountered this problem.

**Closed by daniel31x13** 2024-02-15 13:21 UTC
Labels: bug

**Comment by etec-masterofsynapse** [comment] 2024-02-15 17:07
With the added env var, the entries now all load.

Maybe add this to the docs?
