### ISSUE TITLE
Bulk Move Bookmark to a Collection Based on Search

### ISSUE THREAD

**Issue by jrdwiz** [linkwarden/linkwarden#559] opened 2024-04-13 20:43 UTC
### Environment:

Self Hosted - Debian 12 / Docker 
Version 2.5.1

### Question:

Is it possible to bulk edit / bulk move bookmarks based on a search? (I don't see an edit "pencil" option when searching)
 E.g., search for github.com and then bulk edit all links, moving them to a collection called GitHub.
 
 Hopefully I'm overlooking something simple. Any input would be appreciated.

**Comment by CKextreme** [comment] 2024-12-20 16:03
Currently in v2.8 I see the pencil for bulk edit, but when I move the results to another collection I have totally different links in that collection. So seems still not to work as I would expect...

**Comment by daniel31x13** [comment] 2024-12-29 06:00
Closing this since it’s already implemented, @CKextreme please open a select issue if the bug persists, right now I wasn’t able to reproduce the bug…

**Closed by daniel31x13** 2024-12-29 06:00 UTC
Labels: question
