### ISSUE TITLE
Setup Github Action to publish container images

### ISSUE THREAD

**Issue by peschmae** [linkwarden/linkwarden#165] opened 2023-09-19 10:40 UTC
**Is your feature request related to a problem? Please describe.**
Currently linkwarden doesn't publish any container/docker images.

Using Github actions, it's possible to automatically build container images if a new release is created, and automatiaclly publish it to the github registry.

**Describe the solution you'd like**
I would propose to enable the github actions for the repository, and would be willing to contribute to required github actions/workflows to automatically publish releases as new images.

**Describe alternatives you've considered**
It's also possible to publish to dockerhub, but this would require a organization account on docker hub as well, and just using the github registry would work fine as well.

**Additional context**
There seems to have been some discussions in #11 but it's unclear what the outcome of that was.

**Comment by daniel31x13** [comment] 2023-09-19 13:12
Hello @peschmae,
Thank you for the contribution.
The issue at #11 was for the [previous version](https://github.com/linkwarden/linkwarden-old) and everything has changed since then... (I cleared up the repo and started everything from scratch in this repository, so the [previous version ](https://github.com/linkwarden/linkwarden-old) is basically a duplicate of this repository at an older point in time.)

**Closed** 2023-09-27 05:25 UTC
