### ISSUE TITLE
Profile picture reloads when switching sections

### ISSUE THREAD

**Issue by SoCuul** [linkwarden/linkwarden#167] opened 2023-09-20 05:36 UTC
**Describe the bug**
Whenever I switch sections (dashboard/links/collections), the profile picture reloads. This shows the default profile picture for a fraction of a second before showing my chosen one.

**To Reproduce**
1. Switch tabs

**Expected behavior**
My profile picture should stay loaded when switching sections, instead of showing the default profile picture for a short period of time.

**Screenshots**
https://i.imgur.com/N7aVsXA.mp4

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5.2
 - Browser: Firefox (Release)
 - Version: 116.0.3

**Comment by daniel31x13** [comment] 2023-10-14 17:38
This will be fixed in the next version.

**Comment by daniel31x13** [comment] 2023-10-19 05:04
Fixed in [v1.2.0](https://github.com/linkwarden/linkwarden/releases/tag/v1.2.0).

**Closed by daniel31x13** 2023-10-19 05:04 UTC

**Comment by SoCuul** [comment] 2023-11-10 02:45
For some reason, this bug has popped back up in the most recent release (v2.0.0)

**Comment by daniel31x13** [comment] 2023-11-10 03:48
Hey sorry to hear that, could you provide more context? Because I can't reproduce it.

**Comment by SoCuul** [comment] 2023-11-10 04:35
Here's a video of the bug:
https://github.com/linkwarden/linkwarden/assets/63339559/be416667-2090-43e0-86ac-fb9aa45545d2

Also I just now noticed that the spacing on the links nav bar is slightly different than the other two sections.
